### ISSUE TITLE
Multiple actions for one Feature

### ISSUE THREAD

**Issue by HWDexperte** [HWDexperte/ts3observer#36]
Should it be possible to configure multiple actions for one Feature like this:

```yaml
FeatureXY:
  enable: True
  execute1:
    action: move
    to: 42
    s_delay: 10
  execute2:
    action: kick
    reasonid: 5
    m_delay: 60
    reason: "Idled too long!"
```
